### ISSUE TITLE
PASSWALL2似乎与SFE有冲突（PASSWALL则没有）

### ISSUE THREAD

**Issue by wlmqwyf** [Openwrt-Passwall/openwrt-passwall2#150]
我使用的是Lienol OpenWRT 22.03的源码，R2S的硬件，开启Passwall 2的插件，似乎会导致SFE不能运行，从而使R2S互联网测速只能达到380Mbps左右，关闭Passwall 2插件，则互联网测速能够顺利达到1000Mbps满速状态。同样的硬件和源码，开启Passwall插件，互联网测速可以达到1000Mbps。我不清楚是不是SFE与Passwall 2不兼容导致的，只是通过上述表现猜测。
注明：
1、插件是编译OpenWRT时集成的，Passwall 2 与 Passwall 分别集成，不是同时集成安装的。
2、上述互联网测速指的是国内测速节点，不是境外测速节点。使用的是电信官方测速通道。

**Comment by jdnt** [comment]
SFE貌似不会影响网速，小包转发率平时也感受不出来。有没有可能楼主在passwall2上用了全局代理？

**Comment by wlmqwyf** [comment]
> SFE貌似不会影响网速，小包转发率平时也感受不出来。有没有可能楼主在passwall2上用了全局代理？

如果使用了全局代理，那么我测速的速率将是在100Mbps左右，不会达到300Mbps左右的。因为节点限速100Mbps。很明显是转发的问题。SFE是否会影响网速取决于硬件性能。你用X86架构的CPU，当然感觉不出来。但如果使用ARM或者RISC-V架构的某些性能孱弱的CPU，你就会明显感觉到速率差异了。

**Comment by wlmqwyf** [comment]
> SFE貌似不会影响网速，小包转发率平时也感受不出来。有没有可能楼主在passwall2上用了全局代理？

再给您讲一个我的测试对比。未集成PASSWALL2等翻墙插件，硬件R2S，Lienol 22.03的源码，电信官方测速通道，开启SFE：1000Mbps，关闭SFE：300Mbps；

**Comment by jdnt** [comment]
明白了，我确实没有经常用r2s。有个基友有在用，上次给他编译的是Lean的R22.5.5(5.15.46)+passwall2+SFE，目前没有发现兼容性问题，SFE可以正常启动。不过他家的宽带只有300M，暂时无法验证SFE开启状态时是否有效。
