### ISSUE TITLE
[Bug]: 安装24.11.19-2, iptable 报错

### ISSUE THREAD

**Issue by Brightchu** [Openwrt-Passwall/openwrt-passwall2#698]
### Describe the Bug you encountered

安装24.11.19-2后，启动 passwall2，iptable报如下的错误，passwall2 core 没法启动。
在 1.31.1 以及之前的版本都是正常启动。

/etc/init.d/passwall2 restart

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): interface name `mac:54:xx:xx:xx:xx:96' must be shorter than IFNAMSIZ (15)
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): interface name `mac:54:xx:xx:xx:xx:96' must be shorter than IFNAMSIZ (15)
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): interface name `mac:18:xx:xx:xx:xx:16' must be shorter than IFNAMSIZ (15)
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (legacy): interface name `mac:18:xx:xx:xx:xx:16' must be shorter than IFNAMSIZ (15)
Try `iptables -h' or 'iptables --help' for more information.

我的passwall2 设置里面开启了访问控制，这几个设备 mac 地址来自于我设置的访问控制。
我试过把访问控制的开关关掉，重启 passwall2，依然会报一样的错误。

### Steps to reproduce this Bug

1. 安装 [luci-23.05_luci-app-passwall2_24.11.19_all.ipk](https://github.com/xiaorouji/openwrt-passwall2/releases/download/24.11.19-2/luci-23.05_luci-app-passwall2_24.11.19_all.ipk)
2. 重启 passwall2, /etc/init.d/passwall2 restart

### What you want to implement

解决 iptable 的 error。使得 passwall2 正常启动

### Log information

~# opkg list |grep -E "kernel|iptables"
iptables-mod-conntrack-extra - 1.8.7-8
iptables-mod-extra - 1.8.7-8
iptables-mod-filter - 1.8.7-8
iptables-mod-fullconenat - 2022-02-13-6
iptables-mod-ipopt - 1.8.7-8
iptables-mod-iprange - 1.8.7-8
iptables-mod-nat-extra - 1.8.7-8
iptables-mod-socket - 1.8.7-8
iptables-mod-tproxy - 1.8.7-8
iptables-zz-legacy - 1.8.7-8
kernel - 5.10.221-1
miniupnpd-iptables - 2.3.3-2
nfs-kernel-server - 2.5.4-5
nfs-kernel-server-utils - 2.5.4-5

### System related information

- Passwall2 version: 24.11.19-2
- kernel - 5.10.221-1

**Comment by xiaorouji** [comment]
刪掉對應的訪問控制重新配置一下
